#!/bin/bash

# Create a virtual network using network namespaces and veth pairs
# to connect them.
# Assuming $CONFIGDIR == "cfg":
# * Files in cfg/<Node name> will be overlaid over /etc, i.e. if a file with
# the same name exists in both directory, the one in cfg/<Node name> will
# be the one used.
# * If cfg/<Node name>_$BOOT (defaults to cfg/<Node name>_boot) exists and
# is executable, it will be executed when the node is created
# * If cfg/<Node name>_$STARTUP (defaults to cfg/<Node name>_start) exists and
# is executable, it will be executed when the whole network has started
#

# IMPORTANT NOTE: Node names MUST NOT exceed 9 characters.
# This is due to the limitation to 14 characters of interface names

# You can override any of these settings on a per-topology basis
# Group number
GROUPNUMBER=1
# Node configs  
CONFIGDIR=project_config
# boot script name
BOOT="boot"
# startup script name
STARTUP="start"
PREFIXBASE="fde4:${GROUPNUMBER}"
PREFIXLEN=32
# You can reuse the above two to generate ip addresses/routes, ...
# e.g. "${PREFIXBASE}:1234::/$((PREFIXLEN+16))"

# This function describes the network topology that we want to emulate
function mk_topo {
    echo "@@ Adding links and nodes"
    # Build a small network BELNET - BXL - LLN
    # Nodes are creadted on the fly, and their interface are assigned as
    # <node name>-eth<count>, where count starts at 0 and is increased by 1
    # after each new interface
    # e.g. BXL-eth0 links to LLN-eth0
    add_link P0 P1

    add_link P0 LUX0
    add_link P0 NAM0
    add_link P0 LG0
    add_link P0 BW0

    add_link P1 LUX1
    add_link P1 NAM1
    add_link P1 LG1
    add_link P1 BW1

    add_link LUX0 LUX1
    add_link NAM0 NAM1
    add_link LG0 LG1
    add_link BW0 BW1

    add_link BW0 BX
    add_link BW1 BX

    echo "@@ Adding LANs"
    # Create a new LAN (subnet), attached to BELNET, with 2 hosts: B1 and B2
    ## mk_LAN BELNET B1 B2
    # Same but with 4 hosts in LLN
    ## mk_LAN LLN L1 L2 L3 L4

    echo "@@ Briding the network"
    # Connect BELNET to its two connectivity providers
    bridge_node P0 eth1 P0-eth5
    bridge_node P0 eth5 P0-eth6

    bridge_node P1 eth2 P1-eth5
    bridge_node P1 eth3 P1-eth6
    
    bridge_node BX eth4 BX-eth2
    
    ## bridge_node BELNET eth2 as300
}

