#! /bin/sh
ldconfig

ip link set dev lo up
ip -6 addr add fde4:1:0801::a/128 dev lo

# Assigning IP addr for P1-eth0
ip link set dev BX-eth0 up
ip link set dev BX-eth1 up

# zebra is required to make the link between all FRRouting daemons
# and the linux kernel routing table
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/zebra -A 127.0.0.1 -f /etc/zebra.conf -z /tmp/BX.api -i /tmp/BX_zebra.pid --v6-rr-semantics &
# launching FRRouting OSPF daemon
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/ospf6d -f /etc/BX_ospf.conf -z /tmp/BX.api -i /tmp/BX_ospf6d.pid -A 127.0.0.1 &
# launching FRRouting BGP daemon
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/bgpd -f /etc/BX_bgpd.conf -z /tmp/BX.api -i /tmp/BX_bgpd.pid -A 127.0.0.1 &


