#! /bin/sh
ldconfig

ip link set dev lo up
ip -6 addr add fde4:1:0200::2/128 dev lo

# Assigning IP addr for P1-eth0
ip link set dev LUX0-eth0 up
ip link set dev LUX0-eth1 up

# zebra is required to make the link between all FRRouting daemons
# and the linux kernel routing table
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/zebra -A 127.0.0.1 -f /etc/zebra.conf -z /tmp/LUX0.api -i /tmp/LUX0_zebra.pid &
# launching FRRouting OSPF daemon
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/ospf6d -f /etc/LUX0_ospf.conf -z /tmp/LUX0.api -i /tmp/LUX0_ospf6d.pid -A 127.0.0.1 &


