#! /bin/sh
ldconfig

ip link set dev lo up
ip -6 addr add fde4:1:400::4/128 dev lo

# Assigning IP addr for P1-eth0
ip link set dev NAM0-eth0 up
ip link set dev NAM0-eth1 up
ip link set dev NAM0-eth2 up
ip -6 addr add fde4:3::1:f00d/64 dev NAM0-eth2

# zebra is required to make the link between all FRRouting daemons
# and the linux kernel routing table
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/zebra -A 127.0.0.1 -f /etc/zebra.conf -z /tmp/NAM0.api -i /tmp/NAM0_zebra.pid --v6-rr-semantics &
# launching FRRouting OSPF daemon
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/ospf6d -f /etc/NAM0_ospf.conf -z /tmp/NAM0.api -i /tmp/NAM0_ospf6d.pid -A 127.0.0.1 &
# launching FRRouting BGP daemon
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/bgpd -f /etc/NAM0_bgpd.conf -z /tmp/NAM0.api -i /tmp/NAM0_bgpd.pid -A 127.0.0.1 &


