#! /bin/sh
ldconfig

ip link set dev lo up
ip -6 addr add fde4:1::/128 dev lo

# Assigning IP addr for P1-eth0
ip link set dev P0-eth0 up
ip link set dev P0-eth1 up
ip link set dev P0-eth2 up
ip link set dev P0-eth3 up
ip link set dev P0-eth4 up
ip link set dev P0-eth5 up
ip -6 addr add fde4::1:cafe/64 dev P0-eth5
ip link set dev P0-eth6 up
ip -6 addr add fde4:2:1::1:acdc/64 dev P0-eth6

# zebra is required to make the link between all FRRouting daemons
# and the linux kernel routing table
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/zebra -A 127.0.0.1 -f /etc/zebra.conf -z /tmp/P0.api -i /tmp/P0_zebra.pid --v6-rr-semantics &
# launching FRRouting OSPF daemon
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/ospf6d -f /etc/P0_ospf.conf -z /tmp/P0.api -i /tmp/P0_ospf6d.pid -A 127.0.0.1 &
# launching FRRouting BGP daemon
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/bgpd -f /etc/P0_bgpd.conf -z /tmp/P0.api -i /tmp/P0_bgpd.pid -A 127.0.0.1 &


